#As it stands, all NPlayerPayoffs should only be generated by ScoreParser.
class NPlayerPayoff < ActiveRecord::Base
  belongs_to :n_player_profile
  belongs_to :sample
  belongs_to :player
  
  validates_presence_of :n_player_profile_id
  validates_presence_of :sample_id
  validates_presence_of :player_id
  validates_numericality_of :payoff

  #TODO - validations
end  

  
  
